### ISSUE TITLE
tampilin foto dari wiki 

### ISSUE THREAD

**Issue by fatanugraha** [tirtaabimanyu/tebak-omega#10]
setelah ketebak orangnya, tampilin foto nya dia dari wiki.

**Comment by tirtaabimanyu** [comment]
ini apa kabar

**Comment by fatanugraha** [comment]
cuy udah cuy, woy close issuenya @tirtaabimanyu @apakaden

**Comment by tirtaabimanyu** [comment]
oh iya kocak lah kalian gak ngingetin @fatanugraha @apakaden
